# Usa uma imagem base leve com JRE (Java Runtime Environment)
FROM openjdk:17-jdk-slim

# Cria o diretório de trabalho no container
WORKDIR /app

# Copia o JAR do seu build para o container 
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Expõe a porta que o Spring Boot usa
EXPOSE 8080

# Comando para rodar a aplicação Spring Boot
ENTRYPOINT ["java","-jar","/app.jar"]